### PR TITLE
Wip rockpie

### PR DESCRIPTION
**Pull request by Pix13**

### CODE REVIEW

**Comment by Pix13** [comment]
Driver fixes to build with rockpie kernel

**Comment by pengphei** [comment]
Thank you for your work.

**Comment by Pix13** [comment]
Bad pull request i will come back when its OK :)

**Comment by pengphei** [comment]
@Pix13 As your wish. Just do it ;)

**Comment by Pix13** [comment]
Well it builds but even if it's copied to the staging rootfs, it's not copied to the img final file, so i'll fix that, then test it, then make a proper merge request :)

**Comment by pengphei** [comment]
> Well it builds but even if it's copied to the staging rootfs, it's not copied to the img final file, so i'll fix that, then test it, then make a proper merge request :)

hmmm, are you building it with external kernel? or openwrt builtin kernel?

**Comment by Pix13** [comment]
The openwrt builtin kernel, but i changed the makefile invocation to make it build, using the one that was there did not trigger the build of the module, i don't know why

**Comment by pengphei** [comment]
> The openwrt builtin kernel, but i changed the makefile invocation to make it build, using the one that was there did not trigger the build of the module, i don't know why

during menuconfig process, which mode do you choose for the driver, M for pkg generate or * as pkg generate and install ?

**Comment by Pix13** [comment]
i selected M, but i'm realizing maybe in the openwrt menuconfig it's not like in the kernel one, right.. ? [M] means built as a module and provided only as an ipk, and [*] built as a module and included in the image ?

**Comment by pengphei** [comment]
> i selected M, but i'm realizing maybe in the openwrt menuconfig it's not like in the kernel one, right.. ? [M] means built as a module and provided only as an ipk, and [*] built as a module and included in the image ?

Yes, when selected M, it will just put it in the build directory. and [*] will built as module and included in the image.

**Comment by Pix13** [comment]
Ok i got something, driver loads and gives me 2 radios ( bg only) and thet don't work in openwrt ( yet) :) But it's taking form

**Comment by Pix13** [comment]
https://github.com/openwrt/luci/issues/3733 :( Looking in to that.. indeed iwinfo is pretty empty:

root@OpenWrt:~# iwinfo
wlan0     ESSID: unknown
          Access Point: 7C:A7:B0:20:E8:7A
          Mode: Client  Channel: unknown (unknown)
          Tx-Power: 12 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: unknown
          Encryption: unknown
          Type: nl80211  HW Mode(s): 802.11abg
          Hardware: unknown [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: no  PHY name: phy0

wlan1     ESSID: unknown
          Access Point: 7E:A7:B0:20:E8:7A
          Mode: Client  Channel: unknown (unknown)
          Tx-Power: 12 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: unknown
          Encryption: unknown
          Type: nl80211  HW Mode(s): 802.11abg
          Hardware: unknown [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: no  PHY name: phy1

**Comment by Pix13** [comment]
The chip itself is working as i can scan my surrounding Wireless networks using LuCI

**Pull request closed without merging**
